# Generated by Django 4.0.2 on 2023-03-26 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_img_alter_comment_body_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
